CREATE OR REPLACE trigger Can_Sell
BEFORE insert on INCLUDE
FOR EACH ROW

DECLARE
QUANTITY_INC NUMBER;
QUANTITY_MAG NUMBER;
CANT_SELL EXCEPTION;

BEGIN

SELECT COUNT(*) INTO QUANTITY_MAG FROM CONTENUTO_FORN WHERE :new.CODICE_INCLUDE = CODICE_CONTFORN;
SELECT COUNT(*) INTO QUANTITY_INC FROM INCLUDE WHERE :new.CODICE_INCLUDE = CODICE_INCLUDE;

IF (QUANTITY_INC + :new.QUANTITY_INCLUDE) > QUANTITY_MAG 
THEN RAISE CANT_SELL;
END IF;

EXCEPTION
WHEN CANT_SELL THEN
RAISE_APPLICATION_ERROR(-20004,'CANT SELL MORE THAN YOU HAVE');

END;