CREATE OR REPLACE TRIGGER Max_dip_tot
BEFORE INSERT ON DIPENDENTI
FOR EACH ROW

DECLARE
N_neg NUMBER;
N_dep NUMBER;
N_much EXCEPTION;

BEGIN

SELECT COUNT(*) INTO N_neg FROM NEGOZIO;
SELECT COUNT(*) INTO N_dep FROM DIPENDENTI;

IF (N_dep + 1) > (15*N_neg) THEN 
RAISE N_much;
END IF;

EXCEPTION
WHEN N_much THEN 
RAISE_APPLICATION_ERROR(-20009, 'TOO MANY WORKERS IN THE DB');

END'
