CREATE OR REPLACE TRIGGER Dirigente
BEFORE INSERT OR UPDATE ON NEGOZIO
FOR EACH ROW

DECLARE
Data_Lav DATE;
Cant_manage EXCEPTION;

BEGIN
SELECT DATA_IN_DIP INTO Data_Lav FROM LAVORA_IN WHERE :new.CF_DIRIGENTE_NEG = CF_LAVIN;

IF (:new.DATA_INIZIO_NEG - Data_Lav) < 365
THEN RAISE Cant_manage;
END IF;

EXCEPTION
WHEN Cant_manage THEN
RAISE_APPLICATION_ERROR(-20007, 'CANT MANAGE, HE WORKED FOR LESS THAN A YEAR');

END;
