CREATE OR REPLACE TRIGGER Pres_Max_Time
BEFORE INSERT OR UPDATE ON PRESENZE
FOR EACH ROW

DECLARE
Presence NUMBER;
Nine_hour EXCEPTION;
Twelve_hour EXCEPTION;

BEGIN
SELECT 24*(:new.DATA_FINE_PRES - :new.DATA_INIZIO_PRES) INTO Presence FROM dual;
IF Presence >= 9 AND Presence < 12
THEN RAISE Nine_hour;
END IF;


IF Presence >= 12 
THEN RAISE Twelve_hour;
END IF;


EXCEPTION
WHEN Nine_hour THEN
dbms_output.put_line('YOU ARE WORKING TOO MUCH! MAX HOURS FOR A DAY:8');

WHEN Twelve_hour THEN
RAISE_APPLICATION_ERROR(-20008,'THIS TURN DOESNT COUNT, TOO MANY HOURS');

END;
