CREATE OR REPLACE TRIGGER No_Double_Work
BEFORE INSERT ON LAVORA_IN  
FOR EACH ROW
DECLARE
Double_Work EXCEPTION;
Count_Work NUMBER;
BEGIN
SELECT COUNT(*) INTO Count_Work FROM LAVORA_IN WHERE CF_LAVIN = :new.CF_LAVIN;
IF Count_Work > 0 THEN
RAISE Double_WORK;
END IF;
EXCEPTION
WHEN Double_Work THEN
RAISE_APPLICATION_ERROR(-20001,'INVALID');
END;