CREATE OR REPLACE TRIGGER Stip_fix_dirig
BEFORE INSERT ON STIPENDIO
FOR EACH ROW

DECLARE
Low_money EXCEPTION;
CheckD NUMBER;

BEGIN
SELECT COUNT(*) INTO CheckD FROM NEGOZIO WHERE :new.CF_STIP = CF_DIRIGENTE_NEG;

IF CheckD > 0 THEN
IF :new.IMPORTO < 3200
THEN RAISE Low_money;
END IF;
END IF;

EXCEPTION
WHEN Low_money THEN
RAISE_APPLICATION_ERROR(-20006,'TOO LOW MONEY FOR HIM');
END;