CREATE OR REPLACE TRIGGER Stip_fix_dip
BEFORE INSERT ON STIPENDIO
FOR EACH ROW

DECLARE
Too_money EXCEPTION;
CheckD NUMBER;

BEGIN
SELECT COUNT(*) INTO CheckD FROM NEGOZIO WHERE :new.CF_STIP = CF_DIRIGENTE_NEG;

IF CheckD = 0 THEN
IF :new.IMPORTO > 1900
THEN RAISE Too_money;
END IF;
END IF;

EXCEPTION
WHEN Too_money THEN
RAISE_APPLICATION_ERROR(-20005,'TOO MUCH MONEY FOR HIM');
END;