CREATE OR REPLACE PROCEDURE Scontistica 
IS
Codprod VARCHAR2(30);
BEGIN

FOR x IN(
SELECT CODICE_INCLUDE,QUANTITY_INCLUDE
FROM(SELECT * 
	FROM TESSERA JOIN CARRELLO ON ID_TESSERA = ID_TESSERA_CARRELLO JOIN INCLUDE ON ID_CARRELLO = ID_INCLUDE)
GROUP BY CODICE_INCLUDE,QUANTITY_INCLUDE
HAVING QUANTITY_INCLUDE = (SELECT MAX(QUANTITY_INCLUDE) FROM(SELECT CODICE_INCLUDE,QUANTITY_INCLUDE
FROM(SELECT * 
	FROM TESSERA JOIN CARRELLO ON ID_TESSERA = ID_TESSERA_CARRELLO JOIN INCLUDE ON ID_CARRELLO = ID_INCLUDE)
GROUP BY CODICE_INCLUDE,QUANTITY_INCLUDE)))
LOOP
Codprod:= x.CODICE_INCLUDE;
UPDATE PRODOTTO
SET PREZZO_PRODOTTO = PREZZO_PRODOTTO * 0.7
WHERE CODICE_PRODOTTO = Codprod;
END LOOP;

END Scontistica;


